#!/bin/sh

case "$1" in
    purge)
	systemctl stop libemb-heater-perl
	;;

    remove|upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
	systemctl stop libemb-heater-perl
	;;

    *)
	echo "postrm called with unknown argument \`$1'" >&2
	exit 1
	;;
esac
