#!/bin/sh

case "$1" in
    purge)
	USERNAME=heater
	if [ -x "$(command -v deluser)" ]; then
	    deluser --quiet --system $USERNAME > /dev/null || true
	else
	    echo >&2 "not removing $USERNAME system account because deluser command was not found"
	fi
	;;

    remove|upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
	;;

    *)
	echo "postrm called with unknown argument \`$1'" >&2
	exit 1
	;;
esac
