---
- hosts: emb_heater
  vars:
    emb_heater: "{{ansible_local.emb_heater.default}}"

  tasks:
    - name: Create system configuration files directory
      file: path={{emb_heater.conf_dir}} \
            owner=root \
            group=root \
            mode=0755 \
            state=directory

    - name: Install configuration files to system
      template: src={{emb_heater.template_dir}}{{emb_heater.conf_dir}}/daemon.conf \
                dest={{emb_heater.conf_dir}}/daemon.conf \
                mode=0644 \
                owner=root \
                group=root

    - name: Install systemd service to system
      template: src={{emb_heater.template_dir}}{{emb_heater.systemd_service_dir}}/heater.service \
                dest={{emb_heater.systemd_service_dir}}/heater.service \
                mode=0644 \
                owner=root \
                group=root

    - name: Create log files directory
      file: path={{emb_heater.log_dir}} \
            owner=root \
            group=root \
            mode=0755 \
            state=directory

    - name: Install debian packages
      apt: name=libproc-pid-file-perl,libconfig-simple-perl state=present

    - name: Configure Perl modules
      shell: "cd {{emb_heater.app_dir}} && perl Build.PL"

    - name: Build Perl modules
      shell: "cd {{emb_heater.app_dir}} && ./Build"

    - name: Install Perl dependencies
      shell: "cd {{emb_heater.app_dir}} && ./Build installdeps"

    - name: Install Perl modules
      shell: "cd {{emb_heater.app_dir}} && ./Build install"

    - name: Clean build artefacts
      shell: "cd {{emb_heater.app_dir}} && ./Build realclean"

    - name: Link executables to system path
      command: "ln -s {{emb_heater.app_dir}}/scripts/heater /usr/local/bin/heater"

    - name: Enable heater systemd daemon
      systemd: state=started name=heater enabled=yes

