---
- hosts: emb_heater
  vars:
    emb_heater: "{{ansible_local.system.emb_heater}}"

  tasks:
    - name: Create system configuration files directory
      file: path={{emb_heater.conf_dir}} \
            owner=root \
            group=root \
            mode=0755 \
            state=directory

    - name: Install configuration files to system
      template: src={{emb_heater.template_dir}}/emb-heater/daemon.conf \
                dest={{emb_heater.conf_dir}}/daemon.conf \
                mode=0644 \
                owner=root \
                group=root

    - name: Install debian packages
      apt: name=libproc-pid-file-perl,libconfig-simple-perl state=present

    - name: Configure Perl modules
      shell: "cd {{emb_heater.app_dir}} && perl Build.PL"

    - name: Build Perl modules
      shell: "cd {{emb_heater.app_dir}} && ./Build"

    - name: Install Perl dependencies
      shell: "cd {{emb_heater.app_dir}} && ./Build installdeps"

    - name: Install Perl modules
      shell: "cd {{emb_heater.app_dir}} && ./Build install"

    - name: Clean build artefacts
      shell: "cd {{emb_heater.app_dir}} && ./Build realclean"

    - name: Copy executables to system path
      command: "cp {{emb_heater.app_dir}}/scripts/heater /usr/local/bin/"
